### ISSUE TITLE
NPM repository link is incorrect

### ISSUE THREAD

**Issue by liuy97** [farfromrefug/nativescript-perms#2]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
The repository link is still https://github.com/Akylas/nativescript-perms which does not exist any more.

**Comment by farfromrefug** [comment]
@liuy97 thanks just pushed the fix

**Comment by sido420** [comment]
Still does not work.

Also, Marketplace github link should be added to https://market.nativescript.org/plugins/nativescript-perms/

**Comment by farfromrefug** [comment]
@sido420 thanks will fix it. Also new version for N 7.0 will move to @nativescript-community/perms
